app = "plausible"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[deploy]
  release_command = "db migrate"

[env]
  CLICKHOUSE_DATABASE_URL="http://plausible-clickhouse.internal:8123/plausible_dev"
  LISTEN_IP="::"
  ECTO_IPV6=true

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
